FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
	apt-get install -y \
		build-essential \
		ninja-build \
		meson \
		zlib1g-dev \
		libjpeg-dev \
		cmake \
		libtiff-dev \
		libopenjp2-7-dev \
		libpng-dev \
		libxml2-dev \
		libcairo2-dev \
		libgdk-pixbuf-2.0-dev \
		libzstd-dev \
		libjpeg-turbo8-dev \
		doxygen \
		libsqlite3-dev

