name: Build

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install \
          gcc make autoconf automake libtool pkg-config \
          zlib1g-dev \
          libpng-dev \
          libjpeg-turbo8-dev \
          libtiff5-dev \
          libopenjp2-7-dev \
          libgdk-pixbuf2.0-dev \
          libxml2-dev \
          libsqlite3-dev \
          libcairo2-dev \
          libglib2.0-dev \
          doxygen
    - name: Build
      run: |
        autoreconf -i
        ./configure
        make dist
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: |
          openslide-3.4.1.tar.gz
          openslide-3.4.1.tar.xz
