name: Build

on:
  push:
    branches: [devel]
    tags: ["*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Pack
      run: git archive --format=tar.gz -o openslide.tar.gz --prefix=openslide HEAD
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: openslide.tar.gz
