name: C

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        case "${{ matrix.os }}" in
        ubuntu-latest)
          sudo apt-get update && \
          sudo apt-get install \
            gcc make autoconf automake libtool pkg-config \
            zlib1g-dev \
            libpng-dev \
            libjpeg-turbo8-dev \
            libtiff5-dev \
            libopenjp2-7-dev \
            libgdk-pixbuf2.0-dev \
            libxml2-dev \
            libsqlite3-dev \
            libcairo2-dev \
            libglib2.0-dev \
            doxygen
          ;;
        macos-latest)
          brew install \
            gcc make autoconf automake libtool pkg-config \
            zlib \
            libpng \
            jpeg-turbo \
            libtiff \
            openjpeg \
            gdk-pixbuf \
            libxml2 \
            sqlite \
            cairo \
            glib
          ;;
        esac
    - name: Build
      run: |
        autoreconf -i
        ./configure
        make -j4
    - name: Check exports
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: cd test && ./driver exports
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Install tools
      run: sudo apt-get install doxygen
    - name: Build
      run: |
        basename=openslide-docs-$GITHUB_RUN_NUMBER-$(echo $GITHUB_SHA | cut -c-10)
        mkdir artifact
        cd doc
        doxygen
        mv html ../artifact/${basename}
        echo "basename=${basename}" >> $GITHUB_ENV
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.basename }}
        path: artifact
